# This is a basic workflow to help you get started with Actions

name: Build Electron App

# Workaround until manual triggers will arrive.
# When someones stars the repo, the action is triggered.
# To repeat the action one can unstar and star the repo again.
# But, as you can see few lines below, only the project owner can fully create new app versions
# See full example here: https://dev.to/s_abderemane/manual-trigger-with-github-actions-279e
on:
  watch:
    types: [started]

jobs:
  build:
    if: github.actor == github.event.repository.owner.login
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Change directory
        run: |
          cd react-app
          ls .
          echo 'Test'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      # https://github.com/samuelmeuli/action-electron-builder/blob/master/action.yml
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
            release: false
            package_root: ./react-app
            build_script_name: build
            skip_build: false
            use_vue_cli: false
            github_token: ${{ secrets.github_token }}
        
